apiVersion: v1
kind: Service
metadata:
  name: wallet-enclave
  labels:
    app: wallet-enclave
spec:
  type: ClusterIP
  selector:
    app: wallet-enclave
  ports:
    - name: http
      port: 3377
      targetPort: http
